<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> f354554 (merge conflict resolved)
# Generated by Django 4.0.6 on 2022-08-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
<<<<<<< HEAD
=======
=======
# Generated by Django 4.0.6 on 2022-08-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
>>>>>>> eaeb8de009e9ad4518da51a5278af6ac47aea828
>>>>>>> f354554 (merge conflict resolved)
